### PR TITLE
Simplify workers and add a working junit test

### PR DESCRIPTION
**Pull request by chDame**
Hi,

Please review the small simplifications and decide if it's interesting :)

### CODE REVIEW

**Comment by nevries** [comment]
I really like the direction you're heading. I'd like to ask you to adjust some things:
1. Rebase the PR on the latest commit of c8-iteration2, in particular in the bpmn I think little things need to be adjusted. 
2. Use the Web Modeler for changing the models (reason: results of web and desktop modeler are not binary the same, wich creates unnecessary new versions whenever we deploy the very same model via code and made with Desktop Modeler and with Web Modeler).
3. Make sure that https://github.com/camunda-consulting/showroom-customer-onboarding/blob/c8-iteration2/milestones/V5-Automated%20Version.bpmn is always aligned with https://github.com/camunda-consulting/showroom-customer-onboarding/blob/c8-iteration2/src/main/resources/static/bpmn/customer_onboarding_en.bpmn and https://github.com/camunda-consulting/showroom-customer-onboarding/blob/c8-iteration2/milestones/Risk%20Check.dmn is always aligned with https://github.com/camunda-consulting/showroom-customer-onboarding/blob/c8-iteration2/src/main/resources/static/bpmn/risk_check_en.dmn
4. For the test case(s), you can re-use code from here: https://github.com/camunda-consulting/showroom-customer-onboarding/blob/master/src/main/java/com/camunda/demo/customeronboarding/DemoData.java to create input data

**Comment by chDame** [comment]
> 1. Rebase the PR on the latest commit of c8-iteration2, in particular in the bpmn I think little things need to be adjusted.
Branch seems up to date to me. Your last commits are there too

**Comment by chDame** [comment]
Hi @nevries,

Thanks for your comments! I made the required changes. Please tell me if I missed something :)

**Comment by chDame** [comment]
forms are not able to handle object.attribute variables. So better to restart from scratch with less refacto

**Comment by chDame** [comment]
Hi Ragnar, changes were made and tested :)

**Pull request merged**
